import { supabase } from "@/integrations/supabase/client";
import { PurchaseReturn, PurchaseReturnLine } from "@/types";

export interface CreateReturnParams {
    purchaseId: string;
    reason?: string;
    lines: {
        purchaseLineId: string;
        qty: number;
        notes?: string;
    }[];
}

export async function createPurchaseReturn(params: CreateReturnParams) {
    // 1. Create Return Header
    // Note: return_no is generated by DB trigger
    const { data: returnHeader, error: headerError } = await supabase
        .from('purchase_returns')
        .insert({
            purchase_id: params.purchaseId,
            status: 'draft', // Draft first
            reason: params.reason,
        })
        .select()
        .single();

    if (headerError) throw headerError;

    // 2. Create Return Lines
    const linesToInsert = params.lines.map(line => ({
        return_id: returnHeader.id,
        purchase_line_id: line.purchaseLineId,
        qty: line.qty,
        notes: line.notes,
    }));

    const { error: linesError } = await supabase
        .from('purchase_return_lines')
        .insert(linesToInsert);

    if (linesError) {
        // Rollback header if lines fail (manual cleanup since no storage transaction in client)
        await supabase.from('purchase_returns').delete().eq('id', returnHeader.id);
        throw linesError;
    }

    return returnHeader;
}

export async function triggerAutoJournalReturn(returnId: string) {
    const { data, error } = await supabase.functions.invoke('auto-journal-return', {
        body: { returnId },
    });

    if (error) throw error;
    if (!data.success) throw new Error(data.error || 'Unknown error in auto-journal');

    return data;
}

export async function getPurchaseReturns(purchaseId: string) {
    const { data, error } = await supabase
        .from('purchase_returns')
        .select(`
      *,
      lines:purchase_return_lines (
        *,
        purchase_line:purchase_order_lines (
          variant:product_variants (
             sku_variant
          )
        )
      )
    `)
        .eq('purchase_id', purchaseId)
        .order('created_at', { ascending: false });

    if (error) throw error;
    return data;
}
