import { supabase } from '@/integrations/supabase/client';

export interface StockOpname {
    id: string;
    opname_no: string;
    opname_date: string;
    warehouse_id: string | null;
    status: 'draft' | 'confirmed';
    notes: string | null;
    confirmed_at: string | null;
    confirmed_by: string | null;
    created_at: string;
    updated_at: string;
    created_by: string | null;
}

export interface StockOpnameLine {
    id: string;
    opname_id: string;
    variant_id: string;
    system_qty: number;
    physical_qty: number;
    difference_qty: number;
    unit_cost: number;
    notes: string | null;
    created_at: string;
}

export interface CreateOpnameData {
    opname_date: string;
    warehouse_id?: string | null;
    notes?: string | null;
    lines: {
        variant_id: string;
        system_qty: number;
        physical_qty: number;
        unit_cost: number;
        notes?: string | null;
    }[];
}

export interface OpnameFilters {
    startDate?: string;
    endDate?: string;
    warehouseId?: string;
    status?: string;
}

export const getStockOpnames = async (filters?: OpnameFilters) => {
    let query = supabase
        .from('stock_opname')
        .select('*')
        .order('opname_date', { ascending: false })
        .order('created_at', { ascending: false });

    if (filters?.startDate) {
        query = query.gte('opname_date', filters.startDate);
    }

    if (filters?.endDate) {
        query = query.lte('opname_date', filters.endDate);
    }

    if (filters?.warehouseId) {
        query = query.eq('warehouse_id', filters.warehouseId);
    }

    if (filters?.status) {
        query = query.eq('status', filters.status);
    }

    const { data, error } = await query;

    if (error) throw error;
    return data as StockOpname[];
};

export const getStockOpname = async (id: string) => {
    const { data, error } = await supabase
        .from('stock_opname')
        .select(`
      *,
      stock_opname_lines (*)
    `)
        .eq('id', id)
        .single();

    if (error) throw error;
    return data;
};

export const createStockOpname = async (data: CreateOpnameData) => {
    // 1. Create opname record (opname_no will be auto-generated by trigger)
    const { data: opname, error: opnameError } = await supabase
        .from('stock_opname')
        .insert({
            opname_date: data.opname_date,
            warehouse_id: data.warehouse_id || null,
            notes: data.notes || null,
            status: 'draft',
        } as any) // Type assertion: opname_no is auto-generated by trigger
        .select()
        .single();

    if (opnameError) throw opnameError;

    // 2. Create opname lines
    if (data.lines && data.lines.length > 0) {
        const lines = data.lines.map(line => ({
            opname_id: opname.id,
            variant_id: line.variant_id,
            system_qty: line.system_qty,
            physical_qty: line.physical_qty,
            unit_cost: line.unit_cost,
            notes: line.notes,
        }));

        const { error: linesError } = await supabase
            .from('stock_opname_lines')
            .insert(lines);

        if (linesError) throw linesError;
    }

    return opname;
};

export const confirmStockOpname = async (id: string) => {
    // Call Edge Function to confirm and create journal
    const { error } = await supabase.functions.invoke('auto-journal-opname', {
        body: { opname_id: id },
    });

    if (error) throw error;

    return { success: true };
};
