import { supabase } from '@/integrations/supabase/client';
import type { Tables, TablesInsert } from '@/types';

export type StockOpname = Tables<'stock_opname'>;
export type StockOpnameLine = Tables<'stock_opname_lines'>;

export interface CreateOpnameData {
    opname_date: string;
    warehouse_id?: string | null;
    notes?: string | null;
    lines: {
        variant_id: string;
        system_qty: number;
        physical_qty: number;
        unit_cost: number;
        notes?: string | null;
    }[];
}

export interface OpnameFilters {
    startDate?: string;
    endDate?: string;
    warehouseId?: string;
    status?: string;
}

export const getStockOpnames = async (filters?: OpnameFilters): Promise<StockOpname[]> => {
    let query = supabase
        .from('stock_opname')
        .select('*')
        .order('opname_date', { ascending: false })
        .order('created_at', { ascending: false });

    if (filters?.startDate) {
        query = query.gte('opname_date', filters.startDate);
    }

    if (filters?.endDate) {
        query = query.lte('opname_date', filters.endDate);
    }

    if (filters?.warehouseId) {
        query = query.eq('warehouse_id', filters.warehouseId);
    }

    if (filters?.status) {
        query = query.eq('status', filters.status);
    }

    const { data, error } = await query;

    if (error) throw error;
    return data as StockOpname[];
};

export const getStockOpname = async (id: string): Promise<StockOpname & { stock_opname_lines: StockOpnameLine[] }> => {
    const { data, error } = await supabase
        .from('stock_opname')
        .select(`
      *,
      stock_opname_lines (*)
    `)
        .eq('id', id)
        .single();

    if (error) throw error;
    return data as StockOpname & { stock_opname_lines: StockOpnameLine[] };
};

export const createStockOpname = async (data: CreateOpnameData): Promise<StockOpname> => {
    // 1. Create opname record (opname_no will be auto-generated by trigger)
    const payload: TablesInsert<'stock_opname'> = {
        opname_no: 'AUTO', // Trigger will generate this
        opname_date: data.opname_date,
        warehouse_id: data.warehouse_id || null,
        notes: data.notes || null,
        status: 'draft',
    };

    const { data: opname, error: opnameError } = await supabase
        .from('stock_opname')
        .insert(payload)
        .select()
        .single();

    if (opnameError) throw opnameError;

    // 2. Create opname lines
    if (data.lines && data.lines.length > 0) {
        const lines = data.lines.map(line => ({
            opname_id: opname.id,
            variant_id: line.variant_id,
            system_qty: line.system_qty,
            physical_qty: line.physical_qty,
            unit_cost: line.unit_cost,
            notes: line.notes,
        }));

        const { error: linesError } = await supabase
            .from('stock_opname_lines')
            .insert(lines);

        if (linesError) throw linesError;
    }

    return opname as StockOpname;
};

export const confirmStockOpname = async (id: string): Promise<{ success: true }> => {
    // Call Edge Function to confirm and create journal
    const { data, error } = await supabase.functions.invoke('auto-journal-opname', {
        body: { opname_id: id },
    });

    if (error) throw error;

    return data;
};
