import { useEffect, useState } from "react";
import { useNavigate, useParams, useSearchParams } from "react-router-dom";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { format } from "date-fns";
import { toast } from "sonner";
import { ArrowLeft, Save, Plus, Trash2, PackageCheck, CreditCard, Package, Wallet, Loader2, Pencil, MoreVertical } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
} from "@/components/ui/tabs";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { PageHeader } from "@/components/shared/PageHeader";
import { StatusBadge } from "@/components/shared/StatusBadge";
import { DataTable } from "@/components/shared/DataTable";
import { cn } from "@/lib/utils";
import { useSuppliers } from "@/hooks/use-suppliers";
import { useVariants } from "@/hooks/use-products";
import {
  usePurchase,
  useCreatePurchase,
  useUpdatePurchase,
  useAddPurchaseLine,
  useDeletePurchaseLine,
  useReceivePurchaseLines,
  useConfirmPurchase,
} from "@/hooks/use-purchases";
import { PurchaseLineDialog } from "./PurchaseLineDialog";
import { ReceiveDialog } from "./ReceiveDialog";
import { PaymentDialog } from "./PaymentDialog";
import { ReturnDialog } from "./ReturnDialog";
import { PurchaseReturnList } from "./PurchaseReturnList";
import { PurchaseReceiptList } from "./PurchaseReceiptList";
import { PurchasePaymentList } from "./PurchasePaymentList";
import { PurchaseFinancialSummary } from "./PurchaseFinancialSummary";
import { SmartStatusCard } from "./components/SmartStatusCard";

const purchaseSchema = z.object({
  purchase_no: z.string().optional(),
  supplier_id: z.string().min(1, "Supplier is required"),
  order_date: z.string(),
  expected_date: z.string().optional(),
  notes: z.string().optional(),
});

type PurchaseFormData = z.infer<typeof purchaseSchema>;

export default function PurchaseForm() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const supplierIdFromUrl = searchParams.get("supplier");
  const isEdit = id && id !== "new";

  const { data: purchase, isLoading } = usePurchase(isEdit ? id : "");
  // Calculate isReadOnly AFTER purchase is loaded
  const isReadOnly = isEdit && purchase?.status !== "draft";

  const { data: suppliers } = useSuppliers();
  const createPurchase = useCreatePurchase();
  const updatePurchase = useUpdatePurchase();
  const confirmPurchase = useConfirmPurchase();
  const deleteLine = useDeletePurchaseLine();

  const [showLineDialog, setShowLineDialog] = useState(false);
  const [editingLine, setEditingLine] = useState<any>(null);
  const [showReceiveDialog, setShowReceiveDialog] = useState(false);
  const [showPaymentDialog, setShowPaymentDialog] = useState(false);
  const [showReturnDialog, setShowReturnDialog] = useState(false);

  const form = useForm<PurchaseFormData>({
    resolver: zodResolver(purchaseSchema),
    defaultValues: {
      purchase_no: "",
      supplier_id: "",
      order_date: format(new Date(), "yyyy-MM-dd"),
      expected_date: "",
      notes: "",
    },
  });

  // Note: purchase_no is now auto-generated by database trigger
  // See: supabase/migrations/20260102_refactor_po_logic.sql

  // Auto-populate supplier from URL if provided
  useEffect(() => {
    if (!isEdit && supplierIdFromUrl) {
      form.setValue("supplier_id", supplierIdFromUrl);
    }
  }, [supplierIdFromUrl, isEdit, form]);

  useEffect(() => {
    if (purchase) {
      form.reset({
        purchase_no: purchase.purchase_no,
        supplier_id: purchase.supplier_id,
        order_date: purchase.order_date,
        expected_date: purchase.expected_date ?? "",
        notes: purchase.notes ?? "",
      });
    }
  }, [purchase, form]);

  const onSubmit = (data: PurchaseFormData) => {
    if (isEdit) {
      updatePurchase.mutate({
        id,
        data: {
          expected_date: data.expected_date || null,
          notes: data.notes || null,
          supplier_id: data.supplier_id // In case they changed supplier for a draft
        }
      }, {
        onSuccess: () => {
          // Stay on the form after update
          toast.success("Purchase order updated");
        }
      });
    } else {
      createPurchase.mutate({
        ...data,
        supplier_id: data.supplier_id!, // Non-null assertion as validation handles this
      }, {
        onSuccess: (created) => {
          navigate(`/purchases/${created.id}`, { replace: true });
        }
      });
    }
  };

  const handleConfirmOrder = () => {
    // Validation: Must have items
    if (!purchase?.purchase_order_lines || purchase.purchase_order_lines.length === 0) {
      toast.error("Tidak bisa konfirmasi: Harap tambahkan minimal 1 item barang.");
      return;
    }
    // Validation: Must have supplier
    if (!purchase?.supplier_id) {
      toast.error("Tidak bisa konfirmasi: Harap pilih supplier.");
      return;
    }

    // We only need the ID now, as logic is in backend
    confirmPurchase.mutate(id!, {
      onSuccess: () => {
        navigate("/purchases");
      }
    });
  };

  const lineColumns = [
    {
      key: "variant",
      header: "Variant",
      render: (item: any) => item.product_variants?.sku_variant ?? "-",
    },
    { key: "qty_ordered", header: "Qty Ordered" },
    { key: "qty_received", header: "Qty Received" },
    {
      key: "unit_cost",
      header: "Unit Cost",
      render: (item: any) => `Rp ${(item.unit_cost || 0).toLocaleString()}`,
    },
    {
      key: "subtotal",
      header: "Subtotal",
      render: (item: any) => `Rp ${(item.subtotal || 0).toLocaleString()}`,
    },
    {
      key: "actions",
      header: "",
      render: (item: any) => (
        <div className="flex items-center gap-1">
          <Button
            type="button"
            variant="ghost"
            size="icon"
            onClick={(e) => {
              e.stopPropagation();
              setEditingLine(item);
              setShowLineDialog(true);
            }}
            disabled={purchase?.status !== "draft"}
          >
            <Pencil className="h-4 w-4" />
          </Button>
          <Button
            type="button"
            variant="ghost"
            size="icon"
            onClick={(e) => {
              e.stopPropagation();
              deleteLine.mutate(item.id);
            }}
            disabled={purchase?.status !== "draft"}
          >
            <Trash2 className="h-4 w-4 text-destructive" />
          </Button>
        </div>
      ),
    },
  ];

  // Mobile card view for Lines
  const mobileLineRender = (line: any) => (
    <div className="p-3 space-y-2 relative">
      <div className="flex justify-between items-start pr-8">
        <div>
          <div className="font-medium text-sm">{line.product_variants?.sku_variant}</div>
          <div className="text-xs text-muted-foreground">Order: {line.qty_ordered} • Received: {line.qty_received}</div>
        </div>
        <div className="text-right">
          <div className="font-medium text-sm">Rp {(line.subtotal || 0).toLocaleString()}</div>
          <div className="text-xs text-muted-foreground">@ Rp {(line.unit_cost || 0).toLocaleString()}</div>
        </div>
      </div>

      {purchase?.status === 'draft' && (
        <div className="absolute top-2 right-2 flex flex-col gap-1">
          <Button
            variant="ghost" size="icon" className="h-6 w-6"
            onClick={(e) => { e.stopPropagation(); setEditingLine(line); setShowLineDialog(true); }}
          >
            <Pencil className="h-3 w-3" />
          </Button>
          <Button
            variant="ghost" size="icon" className="h-6 w-6 text-destructive"
            onClick={(e) => { e.stopPropagation(); deleteLine.mutate(line.id); }}
          >
            <Trash2 className="h-3 w-3" />
          </Button>
        </div>
      )}
    </div>
  );

  if (isEdit && (isLoading || !purchase)) {
    return (
      <div className="flex h-[400px] items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
        <span className="ml-2">Memuat data Pesanan...</span>
      </div>
    );
  }

  return (
    <>
      <Form {...form}>
        <form id="purchase-form" onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
          <PageHeader
            title={isEdit ? `Purchase Order: ${purchase?.purchase_no}` : "New Purchase Order"}
            action={
              <div className="flex items-center gap-2">
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => navigate('/purchases')}
                  className="hidden sm:inline-flex"
                >
                  Kembali
                </Button>

                {/* Primary Action Button (Desktop & Mobile) */}
                {isEdit && purchase?.status === 'draft' && (
                  <Button
                    type="button"
                    onClick={handleConfirmOrder}
                    disabled={confirmPurchase.isPending}
                    className="bg-blue-600 hover:bg-blue-700 text-white"
                  >
                    {confirmPurchase.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <PackageCheck className="mr-2 h-4 w-4" />}
                    Konfirmasi
                  </Button>
                )}

                <Button
                  type="submit"
                  form="purchase-form"
                  disabled={createPurchase.isPending || updatePurchase.isPending}
                  variant={isEdit && purchase?.status !== 'draft' ? "outline" : "default"}
                >
                  {(createPurchase.isPending || updatePurchase.isPending) ? (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  ) : (
                    <Save className="mr-2 h-4 w-4" />
                  )}
                  {isEdit ? "Simpan" : "Buat Draft"}
                </Button>

                {/* Secondary Actions Dropdown */}
                {isEdit && (
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <Button variant="outline" size="icon">
                        <MoreVertical className="h-4 w-4" />
                      </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end">
                      <DropdownMenuLabel>Aksi Lainnya</DropdownMenuLabel>
                      <DropdownMenuSeparator />

                      {/* Lifecycle Actions */}
                      {(purchase?.status === 'ordered' || (purchase?.status as string) === 'partial') && (purchase.total_received || 0) < (purchase.total_amount || 0) && (
                        <DropdownMenuItem onClick={() => setShowReceiveDialog(true)}>
                          <Package className="mr-2 h-4 w-4" /> Terima Barang
                        </DropdownMenuItem>
                      )}

                      {(purchase?.status === 'received' || purchase?.status === 'ordered' || (purchase?.status as string) === 'partial') && (purchase.total_paid || 0) < ((purchase.total_amount || 0) - (purchase.total_returned || 0)) && (
                        <DropdownMenuItem onClick={() => setShowPaymentDialog(true)}>
                          <Wallet className="mr-2 h-4 w-4" /> Bayar Tagihan
                        </DropdownMenuItem>
                      )}

                      {(purchase?.status === 'received' || purchase?.status === 'completed' || purchase?.status === 'partial') && (purchase.total_received || 0) > 0 && (
                        <DropdownMenuItem onClick={() => setShowReturnDialog(true)} className="text-destructive w-full cursor-pointer flex items-center">
                          Retur Barang
                        </DropdownMenuItem>
                      )}

                      <DropdownMenuSeparator />

                      <DropdownMenuItem onClick={() => navigate(`/accounting?tab=journals&ref_id=${id}`)}>
                        <CreditCard className="mr-2 h-4 w-4" /> Lihat Jurnal
                      </DropdownMenuItem>
                    </DropdownMenuContent>
                  </DropdownMenu>
                )}
              </div>
            }
          />

          {isEdit && purchase && (
            <SmartStatusCard
              status={purchase.status}
              totalAmount={purchase.total_amount || 0}
              totalReceived={purchase.total_received || 0}
              totalPaid={purchase.total_paid || 0}
              totalReturned={purchase.total_returned || 0}
              totalQty={purchase.total_qty || 0}
              receivedQty={purchase.purchase_order_lines?.reduce((sum: number, line: any) => sum + (line.qty_received || 0), 0) || 0}
              onReceive={() => setShowReceiveDialog(true)}
              onPay={() => setShowPaymentDialog(true)}
            />
          )}

          <div className="grid gap-6 lg:grid-cols-[400px_1fr]">
            {/* LEFT SECTION: Order Details + Financial Summary */}
            <div className="space-y-6">
              <Card>
                <CardHeader className="flex flex-row items-center justify-between">
                  <CardTitle>Order Details</CardTitle>
                  {isEdit && purchase && <StatusBadge status={purchase.status} />}
                </CardHeader>
                <CardContent className="space-y-4">
                  <FormField
                    control={form.control}
                    name="purchase_no"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>PO Number</FormLabel>
                        <FormControl>
                          <Input
                            {...field}
                            placeholder="Auto-generated by system"
                            readOnly
                            className="bg-muted"
                          />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="supplier_id"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Supplier</FormLabel>
                        <Select
                          onValueChange={field.onChange}
                          value={field.value}
                          disabled={isReadOnly}
                        >
                          <FormControl>
                            <SelectTrigger>
                              <SelectValue placeholder="Select supplier" />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent>
                            {suppliers?.map((s) => (
                              <SelectItem key={s.id} value={s.id}>
                                {s.name}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <div className="grid grid-cols-2 gap-4">
                    <FormField
                      control={form.control}
                      name="order_date"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>Order Date</FormLabel>
                          <FormControl>
                            <Input {...field} type="date" disabled={isReadOnly} />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    <FormField
                      control={form.control}
                      name="expected_date"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>Expected Date</FormLabel>
                          <FormControl>
                            <Input {...field} type="date" disabled={isReadOnly} />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                  </div>

                  <FormField
                    control={form.control}
                    name="notes"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Notes</FormLabel>
                        <FormControl>
                          <Textarea {...field} disabled={isReadOnly} />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  {/* Internal submit button removed in favor of header action */}
                </CardContent>
              </Card>

              {isEdit && purchase && (
                <PurchaseFinancialSummary
                  totalAmount={purchase.total_amount || 0}
                  totalReceived={purchase.total_received || 0}
                  totalPaid={purchase.total_paid || 0}
                  totalReturned={purchase.total_returned || 0}
                />
              )}
            </div>

            {/* RIGHT SECTION: Tabs (Items, Receipts, Payments, Returns) */}
            {isEdit && (
              <div className="space-y-6">
                <Tabs defaultValue="items" className="w-full">
                  <TabsList className="grid w-full grid-cols-4">
                    <TabsTrigger value="items">Barang</TabsTrigger>
                    <TabsTrigger value="receipts">Penerimaan</TabsTrigger>
                    <TabsTrigger value="payments">Pembayaran</TabsTrigger>
                    <TabsTrigger value="returns">Retur</TabsTrigger>
                  </TabsList>

                  <TabsContent value="items" className="mt-4">
                    <Card>
                      <CardHeader className="flex flex-row items-center justify-between">
                        <CardTitle>Order Lines</CardTitle>
                        {purchase?.status === "draft" && (
                          <Button
                            type="button"
                            size="sm"
                            onClick={() => {
                              setEditingLine(null);
                              setShowLineDialog(true);
                            }}
                          >
                            <Plus className="h-4 w-4 mr-2" />
                            Add Item
                          </Button>
                        )}
                      </CardHeader>
                      <CardContent>
                        <DataTable
                          columns={lineColumns}
                          data={purchase?.purchase_order_lines ?? []}
                          emptyMessage="Belum ada item."
                          mobileCardRender={mobileLineRender}
                        />

                        {purchase?.purchase_order_lines && purchase.purchase_order_lines.length > 0 && (
                          <div className="mt-4 p-4 bg-muted/50 rounded-lg flex flex-col gap-2">
                            <div className="flex justify-between items-center text-sm">
                              <span className="text-muted-foreground">Total Quantity:</span>
                              <span className="font-semibold">{purchase.total_qty} items</span>
                            </div>
                            <div className="flex justify-between items-center text-lg border-t pt-2">
                              <span className="font-bold">Total Amount:</span>
                              <span className="font-bold text-primary">
                                Rp {(purchase.total_amount || 0).toLocaleString('id-ID')}
                              </span>
                            </div>
                          </div>
                        )}
                      </CardContent>
                    </Card>
                  </TabsContent>

                  <TabsContent value="receipts" className="mt-4">
                    <Card>
                      <CardHeader>
                        <CardTitle>Riwayat Penerimaan</CardTitle>
                      </CardHeader>
                      <CardContent>
                        <PurchaseReceiptList purchaseId={id!} />
                      </CardContent>
                    </Card>
                  </TabsContent>

                  <TabsContent value="payments" className="mt-4">
                    <Card>
                      <CardHeader>
                        <CardTitle>Riwayat Pembayaran</CardTitle>
                      </CardHeader>
                      <CardContent>
                        <PurchasePaymentList purchaseId={id!} />
                      </CardContent>
                    </Card>
                  </TabsContent>

                  <TabsContent value="returns" className="mt-4">
                    <Card>
                      <CardHeader>
                        <CardTitle>Riwayat Retur</CardTitle>
                      </CardHeader>
                      <CardContent>
                        <PurchaseReturnList purchaseId={id!} />
                      </CardContent>
                    </Card>
                  </TabsContent>
                </Tabs>
              </div>
            )}
          </div>

        </form>
      </Form>
      {
        isEdit && (
          <>
            <PurchaseLineDialog
              open={showLineDialog}
              onOpenChange={(open) => {
                setShowLineDialog(open);
                if (!open) setEditingLine(null);
              }}
              purchaseId={id!}
              initialData={editingLine}
            />
            <ReceiveDialog
              open={showReceiveDialog}
              onOpenChange={setShowReceiveDialog}
              purchase={purchase}
            />
            <PaymentDialog
              open={showPaymentDialog}
              onOpenChange={setShowPaymentDialog}
              purchase={purchase}
            />
            <ReturnDialog
              open={showReturnDialog}
              onOpenChange={setShowReturnDialog}
              purchase={purchase}
            />
          </>
        )
      }
    </>
  );
}
