import { useEffect, useState } from "react";
import { useNavigate, useParams, useSearchParams } from "react-router-dom";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { format } from "date-fns";
import { toast } from "sonner";
import { ArrowLeft, Save, Plus, Trash2, PackageCheck, CreditCard, Package, Wallet, Loader2, Pencil } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { PageHeader } from "@/components/shared/PageHeader";
import { StatusBadge } from "@/components/shared/StatusBadge";
import { DataTable } from "@/components/shared/DataTable";
import { cn } from "@/lib/utils";
import { useSuppliers } from "@/hooks/use-suppliers";
import { useVariants } from "@/hooks/use-products";
import {
  usePurchase,
  useCreatePurchase,
  useUpdatePurchase,
  useAddPurchaseLine,
  useDeletePurchaseLine,
  useReceivePurchaseLines,
  useConfirmPurchase,
} from "@/hooks/use-purchases";
import { PurchaseLineDialog } from "./PurchaseLineDialog";
import { ReceiveDialog } from "./ReceiveDialog";
import { PaymentDialog } from "./PaymentDialog";
import { ReturnDialog } from "./ReturnDialog";
import { PurchaseReturnList } from "./PurchaseReturnList";

const purchaseSchema = z.object({
  purchase_no: z.string().optional(),
  supplier_id: z.string().min(1, "Supplier is required"),
  order_date: z.string(),
  expected_date: z.string().optional(),
  notes: z.string().optional(),
});

type PurchaseFormData = z.infer<typeof purchaseSchema>;

export default function PurchaseForm() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const supplierIdFromUrl = searchParams.get("supplier");
  const isEdit = id && id !== "new";

  const { data: purchase, isLoading } = usePurchase(isEdit ? id : "");
  // Calculate isReadOnly AFTER purchase is loaded
  const isReadOnly = isEdit && purchase?.status !== "draft";

  const { data: suppliers } = useSuppliers();
  const createPurchase = useCreatePurchase();
  const updatePurchase = useUpdatePurchase();
  const confirmPurchase = useConfirmPurchase();
  const deleteLine = useDeletePurchaseLine();

  const [showLineDialog, setShowLineDialog] = useState(false);
  const [editingLine, setEditingLine] = useState<any>(null);
  const [showReceiveDialog, setShowReceiveDialog] = useState(false);
  const [showPaymentDialog, setShowPaymentDialog] = useState(false);
  const [showReturnDialog, setShowReturnDialog] = useState(false);

  const form = useForm<PurchaseFormData>({
    resolver: zodResolver(purchaseSchema),
    defaultValues: {
      purchase_no: "",
      supplier_id: "",
      order_date: format(new Date(), "yyyy-MM-dd"),
      expected_date: "",
      notes: "",
    },
  });

  // Note: purchase_no is now auto-generated by database trigger
  // See: supabase/migrations/20260102_refactor_po_logic.sql

  // Auto-populate supplier from URL if provided
  useEffect(() => {
    if (!isEdit && supplierIdFromUrl) {
      form.setValue("supplier_id", supplierIdFromUrl);
    }
  }, [supplierIdFromUrl, isEdit, form]);

  useEffect(() => {
    if (purchase) {
      form.reset({
        purchase_no: purchase.purchase_no,
        supplier_id: purchase.supplier_id,
        order_date: purchase.order_date,
        expected_date: purchase.expected_date ?? "",
        notes: purchase.notes ?? "",
      });
    }
  }, [purchase, form]);

  const onSubmit = (data: PurchaseFormData) => {
    if (isEdit) {
      updatePurchase.mutate({
        id,
        data: {
          expected_date: data.expected_date || null,
          notes: data.notes || null,
          supplier_id: data.supplier_id // In case they changed supplier for a draft
        }
      }, {
        onSuccess: () => {
          // Stay on the form after update
          toast.success("Purchase order updated");
        }
      });
    } else {
      createPurchase.mutate({
        ...data,
        supplier_id: data.supplier_id!, // Non-null assertion as validation handles this
      }, {
        onSuccess: (created) => {
          navigate(`/purchases/${created.id}`, { replace: true });
        }
      });
    }
  };

  const handleConfirmOrder = () => {
    // We only need the ID now, as logic is in backend
    confirmPurchase.mutate(id!, {
      onSuccess: () => {
        navigate("/purchases");
      }
    });
  };

  const lineColumns = [
    {
      key: "variant",
      header: "Variant",
      render: (item: any) => item.product_variants?.sku_variant ?? "-",
    },
    { key: "qty_ordered", header: "Qty Ordered" },
    { key: "qty_received", header: "Qty Received" },
    {
      key: "unit_cost",
      header: "Unit Cost",
      render: (item: any) => `Rp ${(item.unit_cost || 0).toLocaleString()}`,
    },
    {
      key: "subtotal",
      header: "Subtotal",
      render: (item: any) => `Rp ${(item.subtotal || 0).toLocaleString()}`,
    },
    {
      key: "actions",
      header: "",
      render: (item: any) => (
        <div className="flex items-center gap-1">
          <Button
            type="button"
            variant="ghost"
            size="icon"
            onClick={(e) => {
              e.stopPropagation();
              setEditingLine(item);
              setShowLineDialog(true);
            }}
            disabled={purchase?.status !== "draft"}
          >
            <Pencil className="h-4 w-4" />
          </Button>
          <Button
            type="button"
            variant="ghost"
            size="icon"
            onClick={(e) => {
              e.stopPropagation();
              deleteLine.mutate(item.id);
            }}
            disabled={purchase?.status !== "draft"}
          >
            <Trash2 className="h-4 w-4 text-destructive" />
          </Button>
        </div>
      ),
    },
  ];

  if (isEdit && (isLoading || !purchase)) {
    return (
      <div className="flex h-[400px] items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
        <span className="ml-2">Memuat data Pesanan...</span>
      </div>
    );
  }

  return (
    <>
      <Form {...form}>
        <form id="purchase-form" onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
          <PageHeader
            title={isEdit ? `Purchase Order: ${purchase?.purchase_no}` : "New Purchase Order"}
            action={
              <div className="flex flex-col sm:flex-row gap-2 justify-end">
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => navigate('/purchases')}
                  className="w-full sm:w-auto"
                >
                  Batal
                </Button>

                {isEdit && (purchase?.status === 'ordered' || (purchase?.status as string) === 'partial') && (
                  <Button
                    type="button"
                    onClick={() => setShowReceiveDialog(true)}
                    className="w-full sm:w-auto bg-orange-600 hover:bg-orange-700 text-white"
                  >
                    <Package className="mr-2 h-4 w-4" />
                    Terima Barang
                  </Button>
                )}

                {isEdit && (purchase?.status === 'received' || purchase?.status === 'ordered' || (purchase?.status as string) === 'partial') && (
                  <Button
                    type="button"
                    onClick={() => setShowPaymentDialog(true)}
                    className="w-full sm:w-auto bg-green-600 hover:bg-green-700 text-white"
                  >
                    <Wallet className="mr-2 h-4 w-4" />
                    Bayar / Pelunasan
                  </Button>
                )}

                {isEdit && (purchase?.status === 'received' || purchase?.status === 'completed' || purchase?.status === 'partial') && (
                  <Button
                    type="button"
                    onClick={() => setShowReturnDialog(true)}
                    variant="destructive"
                    className="w-full sm:w-auto"
                  >
                    Retur Barang
                  </Button>
                )}

                {isEdit && purchase?.status === 'completed' && (
                  <Button
                    type="button"
                    onClick={() => setShowPaymentDialog(true)}
                    variant="outline"
                    className="w-full sm:w-auto"
                  >
                    <Wallet className="mr-2 h-4 w-4" />
                    Riwayat Pembayaran
                  </Button>
                )}

                {/* Journal Drill-down Button */}
                {isEdit && (purchase?.status === 'ordered' || purchase?.status === 'received' || purchase?.status === 'completed' || (purchase?.status as string) === 'partial') && (
                  <Button
                    type="button"
                    variant="ghost"
                    className="w-full sm:w-auto border-dashed border-2"
                    onClick={() => navigate(`/accounting?tab=journals&ref_id=${id}`)}
                  >
                    <CreditCard className="mr-2 h-4 w-4" />
                    Lihat Jurnal
                  </Button>
                )}

                {isEdit && purchase?.status === 'draft' && (
                  <Button
                    type="button"
                    onClick={handleConfirmOrder}
                    disabled={confirmPurchase.isPending || updatePurchase.isPending}
                    className="w-full sm:w-auto bg-blue-600 hover:bg-blue-700 text-white"
                  >
                    {confirmPurchase.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <PackageCheck className="mr-2 h-4 w-4" />}
                    Konfirmasi Pesanan
                  </Button>
                )}

                <Button
                  type="submit"
                  form="purchase-form"
                  disabled={createPurchase.isPending || updatePurchase.isPending}
                  className="w-full sm:w-auto"
                >
                  {(createPurchase.isPending || updatePurchase.isPending) ? (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  ) : (
                    <Save className="mr-2 h-4 w-4" />
                  )}
                  {isEdit ? (purchase?.status === 'draft' ? "Update Draft" : "Update Order") : "Simpan Draft"}
                </Button>
              </div>
            }
          />

          <div className="grid gap-6 lg:grid-cols-3">
            <Card className={cn(isEdit ? "lg:col-span-1" : "lg:col-span-3 max-w-2xl")}>
              <CardHeader className="flex flex-row items-center justify-between">
                <CardTitle>Order Details</CardTitle>
                {isEdit && purchase && <StatusBadge status={purchase.status} />}
              </CardHeader>
              <CardContent className="space-y-4">
                <FormField
                  control={form.control}
                  name="purchase_no"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>PO Number</FormLabel>
                      <FormControl>
                        <Input
                          {...field}
                          placeholder="Auto-generated by system"
                          readOnly
                          className="bg-muted"
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="supplier_id"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Supplier</FormLabel>
                      <Select
                        onValueChange={field.onChange}
                        value={field.value}
                        disabled={isReadOnly}
                      >
                        <FormControl>
                          <SelectTrigger>
                            <SelectValue placeholder="Select supplier" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          {suppliers?.map((s) => (
                            <SelectItem key={s.id} value={s.id}>
                              {s.name}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <div className="grid grid-cols-2 gap-4">
                  <FormField
                    control={form.control}
                    name="order_date"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Order Date</FormLabel>
                        <FormControl>
                          <Input {...field} type="date" disabled={isReadOnly} />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="expected_date"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Expected Date</FormLabel>
                        <FormControl>
                          <Input {...field} type="date" disabled={isReadOnly} />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>

                <FormField
                  control={form.control}
                  name="notes"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Notes</FormLabel>
                      <FormControl>
                        <Textarea {...field} disabled={isReadOnly} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {/* Internal submit button removed in favor of header action */}
              </CardContent>
            </Card>

            {isEdit && (
              <Card className="lg:col-span-2">
                <CardHeader className="flex flex-row items-center justify-between">
                  <CardTitle>Order Lines</CardTitle>
                  {purchase?.status === "draft" && (
                    <Button
                      type="button"
                      size="sm"
                      onClick={() => {
                        setEditingLine(null);
                        setShowLineDialog(true);
                      }}
                    >
                      <Plus className="h-4 w-4 mr-2" />
                      Add Item
                    </Button>
                  )}
                </CardHeader>
                <CardContent>
                  <DataTable
                    columns={lineColumns}
                    data={purchase?.purchase_order_lines ?? []}
                    emptyMessage="Belum ada item. Klik 'Add Item' untuk menambah barang."
                  />

                  {purchase?.purchase_order_lines && purchase.purchase_order_lines.length > 0 && (
                    <div className="mt-4 p-4 bg-muted/50 rounded-lg flex flex-col gap-2">
                      <div className="flex justify-between items-center text-sm">
                        <span className="text-muted-foreground">Total Quantity:</span>
                        <span className="font-semibold">{purchase.total_qty} items</span>
                      </div>
                      <div className="flex justify-between items-center text-lg border-t pt-2">
                        <span className="font-bold">Total Amount:</span>
                        <span className="font-bold text-primary">
                          Rp {(purchase.total_amount || 0).toLocaleString('id-ID')}
                        </span>
                      </div>
                    </div>
                  )}
                </CardContent>
              </Card>
            )}

            {isEdit && <PurchaseReturnList purchaseId={id!} />}
          </div>

        </form>
      </Form>
      {
        isEdit && (
          <>
            <PurchaseLineDialog
              open={showLineDialog}
              onOpenChange={(open) => {
                setShowLineDialog(open);
                if (!open) setEditingLine(null);
              }}
              purchaseId={id!}
              initialData={editingLine}
            />
            <ReceiveDialog
              open={showReceiveDialog}
              onOpenChange={setShowReceiveDialog}
              purchase={purchase}
            />
            <PaymentDialog
              open={showPaymentDialog}
              onOpenChange={setShowPaymentDialog}
              purchase={purchase}
            />
            <ReturnDialog
              open={showReturnDialog}
              onOpenChange={setShowReturnDialog}
              purchase={purchase}
            />
          </>
        )
      }
    </>
  );
}
