-- DISABLE RLS FOR ALL TABLES (DEV MODE)
-- For development/testing WITHOUT authentication system
-- ⚠️ DO NOT USE IN PRODUCTION

-- Master Data
ALTER TABLE customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
ALTER TABLE product_variants DISABLE ROW LEVEL SECURITY;
ALTER TABLE suppliers DISABLE ROW LEVEL SECURITY;
ALTER TABLE brands DISABLE ROW LEVEL SECURITY;
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE units DISABLE ROW LEVEL SECURITY;
ALTER TABLE variant_attributes DISABLE ROW LEVEL SECURITY;
ALTER TABLE attribute_values DISABLE ROW LEVEL SECURITY;
ALTER TABLE product_suppliers DISABLE ROW LEVEL SECURITY;
ALTER TABLE product_images DISABLE ROW LEVEL SECURITY;
ALTER TABLE product_variant_price_history DISABLE ROW LEVEL SECURITY;

-- Transaction Tables
ALTER TABLE sales_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE order_items DISABLE ROW LEVEL SECURITY; -- Corrected name
ALTER TABLE sales_returns DISABLE ROW LEVEL SECURITY;
ALTER TABLE sales_return_lines DISABLE ROW LEVEL SECURITY;
ALTER TABLE sales_imports DISABLE ROW LEVEL SECURITY;
ALTER TABLE marketplace_payouts DISABLE ROW LEVEL SECURITY;

ALTER TABLE purchases DISABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_order_lines DISABLE ROW LEVEL SECURITY; -- Corrected name
ALTER TABLE purchase_returns DISABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_return_lines DISABLE ROW LEVEL SECURITY;

-- Inventory
ALTER TABLE stock_movements DISABLE ROW LEVEL SECURITY; -- Corrected name

-- Finance / Accounting
ALTER TABLE chart_of_accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE journal_entries DISABLE ROW LEVEL SECURITY;
ALTER TABLE journal_lines DISABLE ROW LEVEL SECURITY;
ALTER TABLE journal_account_mappings DISABLE ROW LEVEL SECURITY;
ALTER TABLE bank_accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE accounting_periods DISABLE ROW LEVEL SECURITY;

-- Settings
ALTER TABLE app_settings DISABLE ROW LEVEL SECURITY;

-- Verify
SELECT tablename, rowsecurity 
FROM pg_tables 
WHERE schemaname = 'public' 
ORDER BY tablename;
