import { useState, useEffect } from "react";
import { useForm, useFieldArray } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Plus, Trash2, Check, ChevronsUpDown, PackageSearch } from "lucide-react";
import { toast } from "sonner";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from "@/components/ui/command";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { cn } from "@/lib/utils";
import { useProducts } from "@/hooks/use-products";
import { useCustomers } from "@/hooks/use-customers";
import { useCustomerTypePricing } from "@/hooks/use-customer-pricing";
import { useCreateSalesOrder, useUpdateSalesOrder } from "@/hooks/use-sales";
import { SalesReturnDialog } from "./SalesReturnDialog";

const orderItemSchema = z.object({
  variant_id: z.string().min(1, "Pilih produk"),
  qty: z.coerce.number().min(1, "Min 1"),
  unit_price: z.coerce.number().min(0, "Min 0"),
  hpp: z.coerce.number().min(0, "Min 0"),
});

const formSchema = z.object({
  // order_no removed - auto-generated by sequence
  order_date: z.string().min(1, "Tanggal wajib diisi"),
  marketplace: z.string().optional(),
  customer_id: z.string().optional(),
  customer_name: z.string().max(200).optional(),
  status: z.enum(["pending", "completed", "cancelled", "returned"]),
  total_fees: z.coerce.number().min(0, "Min 0"),
  items: z.array(orderItemSchema).min(1, "Minimal 1 item"),
});

type FormData = z.infer<typeof formSchema>;

interface SalesOrderDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  initialData?: any; // Add initialData prop
}

export function SalesOrderDialog({ open, onOpenChange, initialData }: SalesOrderDialogProps) {
  const { data: products } = useProducts();
  const { data: customers } = useCustomers(); // Add customers hook for discount calculation

  // Pricing Logic
  // We need to watch customer_id to determine the active customer type
  // NOTE: This cannot be done via form.watch() here because form is defined below.
  // We will access form via the form object after definition, or move form definition up?
  // React Hook Form rules: useForm must be at top level.
  // We can't use form.watch here before form is defined.
  // We have to split this.

  // WAIT: I can't access form.watch before useForm.
  // I need to insert the logic AFTER useForm.
  const createOrder = useCreateSalesOrder();
  const updateOrder = useUpdateSalesOrder();
  const [showReturnDialog, setShowReturnDialog] = useState(false);

  const form = useForm<FormData>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      order_date: new Date().toISOString().split("T")[0],
      marketplace: "",
      customer_id: "",
      customer_name: "",
      status: "pending", // ERP Standard: default to pending
      total_fees: 0,
      items: [{ variant_id: "", qty: 1, unit_price: 0, hpp: 0 }],
    },
  });

  const { fields, append, remove } = useFieldArray({
    control: form.control,
    name: "items",
  });

  // Pre-fill form when initialData changes
  useEffect(() => {
    if (open) {
      if (initialData) {
        form.reset({
          order_date: initialData.order_date,
          marketplace: initialData.marketplace || "",
          customer_id: initialData.customer_id || "",
          customer_name: initialData.customer_name || "",
          status: initialData.status,
          total_fees: initialData.total_fees || 0,
          items: initialData.order_items?.map((item: any) => ({
            variant_id: item.variant_id,
            qty: item.qty,
            unit_price: item.unit_price,
            hpp: 0,
          })) || [],
        });
      } else {
        form.reset({
          order_date: new Date().toISOString().split("T")[0],
          marketplace: "",
          customer_id: "",
          customer_name: "",
          status: "pending",
          total_fees: 0,
          items: [{ variant_id: "", qty: 1, unit_price: 0, hpp: 0 }],
        });
      }
    }
  }, [open, initialData, form]);

  // Build variant options from products with stock info
  const variantOptions = products?.flatMap((product) =>
    product.product_variants?.map((variant: any) => ({
      id: variant.id,
      label: `${product.name} - ${variant.sku_variant}`,
      price: variant.price,
      stock: variant.stock_qty || 0,
      productName: product.name,
      sku: variant.sku_variant,
      baseHpp: product.base_hpp || 0,
      productType: product.product_type || 'purchased',
    })) ?? []
  ) ?? [];

  const isReadOnly = initialData?.status === 'completed';

  // Pricing Logic - Watch Customer
  const selectedCustomerId = form.watch("customer_id");
  const activeCustomer = customers?.find(c => c.id === selectedCustomerId);
  const { data: pricingRules } = useCustomerTypePricing(activeCustomer?.customer_type_id);

  const handleVariantChange = (index: number, variantId: string) => {
    const variant = variantOptions.find((v) => v.id === variantId);
    if (variant) {
      let finalPrice = variant.price;
      let isSpecialPrice = false;

      // Check Customer Type Pricing (Special Price)
      if (pricingRules) {
        const specificRule = pricingRules.find(r => r.variant_id === variantId);
        if (specificRule) {
          finalPrice = specificRule.price;
          isSpecialPrice = true;
        }
      }

      form.setValue(`items.${index}.unit_price`, finalPrice);

      // Auto-fill HPP (Frozen at time of sale)
      // Logic: Use product.base_hpp as default
      const defaultHpp = variant.baseHpp;
      form.setValue(`items.${index}.hpp`, defaultHpp);

      if (isSpecialPrice) {
        toast.info("Harga Khusus diterapkan");
      }
    }
  };

  const onSubmit = async (data: FormData) => {
    // Simple pricing - no frozen discount calculation needed
    const items = data.items;
    const totalAmount = items.reduce((sum, item) => sum + (item.qty * item.unit_price), 0);

    const payload = {
      // order_no removed - auto-generated by API
      order_date: data.order_date,
      marketplace: data.marketplace,
      customer_id: data.customer_id,
      customer_name: data.customer_name,
      status: data.status,

      // FROZEN PRICING (ERP Standard)

      total_amount: totalAmount,

      total_fees: data.total_fees,
      items: data.items.map(item => ({
        variant_id: item.variant_id,
        qty: item.qty,
        unit_price: item.unit_price,
        hpp: item.hpp,
      })),
    };

    try {
      if (initialData) {
        await updateOrder.mutateAsync({ id: initialData.id, data: payload as any });
      } else {
        await createOrder.mutateAsync(payload);
      }
      form.reset();
      onOpenChange(false);
    } catch (error) {
      // Error handled in hook
    }
  };

  // Calculate totals
  const items = form.watch("items");
  const totalFees = form.watch("total_fees") || 0;

  const totalAmount = items.reduce((sum, item) =>
    sum + (item.qty || 0) * (item.unit_price || 0), 0
  );
  const totalHpp = items.reduce((sum, item) =>
    sum + (item.qty || 0) * (item.hpp || 0), 0
  );
  const profit = totalAmount - totalHpp - totalFees;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>{initialData ? "Edit Sales Order" : "Tambah Sales Order"}</DialogTitle>
        </DialogHeader>

        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
            {/* Show Auto-Generated Order Number (Read-Only, when editing) */}
            {/* Order Number Display */}
            <div className="flex gap-4">
              <div className="bg-muted/50 p-3 rounded-md border flex-1">
                <div className="text-xs text-muted-foreground">Order Number</div>
                <div className="font-mono font-medium text-lg">
                  {initialData?.order_no || initialData?.desty_order_no || "Auto-Generated (New Order)"}
                </div>
              </div>
              {isReadOnly && (
                <div className="bg-blue-50 border-blue-200 p-3 rounded-md border flex items-center justify-center px-6">
                  <div className="text-blue-700 font-medium flex items-center gap-2">
                    <Check className="h-4 w-4" />
                    Completed (Read-Only)
                  </div>
                </div>
              )}
            </div>

            <div className="grid grid-cols-2 gap-4">
              {/* Customer Selector - Full Width */}
              <div className="col-span-2">
                <FormField
                  control={form.control}
                  name="customer_id"
                  render={({ field }) => (
                    <FormItem className="flex flex-col">
                      <FormLabel>Customer</FormLabel>
                      <Popover>
                        <PopoverTrigger asChild>
                          <FormControl>
                            <Button
                              disabled={isReadOnly}
                              variant="outline"
                              role="combobox"
                              className={cn(
                                "w-full justify-between font-normal",
                                !field.value && "text-muted-foreground"
                              )}
                            >
                              {field.value
                                ? customers?.find((c) => c.id === field.value)?.name
                                : "Pilih customer (Walk-in / Umum)"}
                              <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
                            </Button>
                          </FormControl>
                        </PopoverTrigger>
                        <PopoverContent className="w-[300px] p-0" align="start">
                          <Command>
                            <CommandInput placeholder="Search customer..." />
                            <CommandList>
                              <CommandEmpty>No customer found.</CommandEmpty>
                              <CommandGroup className="max-h-64 overflow-auto">
                                {customers?.map((customer) => (
                                  <CommandItem
                                    key={customer.id}
                                    value={customer.name}
                                    onSelect={() => {
                                      field.onChange(customer.id);
                                      form.setValue("customer_name", customer.name);
                                    }}
                                  >
                                    <Check
                                      className={cn(
                                        "mr-2 h-4 w-4",
                                        customer.id === field.value ? "opacity-100" : "opacity-0"
                                      )}
                                    />
                                    <div className="flex flex-col">
                                      <span className="font-medium">{customer.name}</span>
                                      <span className="text-xs text-muted-foreground">
                                        {customer.code} •
                                        <span className={`ml-1 px-1.5 py-0.5 rounded ${customer.customer_type === 'khusus'
                                          ? 'bg-purple-100 text-purple-700'
                                          : 'bg-blue-100 text-blue-700'
                                          }`}>
                                          {customer.customer_type === 'khusus' ? 'Khusus' : 'Umum'}
                                        </span>
                                      </span>
                                    </div>
                                  </CommandItem>
                                ))}
                              </CommandGroup>
                            </CommandList>
                          </Command>
                        </PopoverContent>
                      </Popover>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>

              {/* Date Field */}
              <FormField
                control={form.control}
                name="order_date"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Tanggal *</FormLabel>
                    <FormControl>
                      <Input type="date" {...field} disabled={isReadOnly} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              {/* Status Field */}
              <FormField
                control={form.control}
                name="status"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Status *</FormLabel>
                    <Select onValueChange={field.onChange} value={field.value} disabled={isReadOnly}>
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        <SelectItem value="pending">Pending</SelectItem>
                        <SelectItem value="completed">Completed</SelectItem>
                        <SelectItem value="cancelled">Cancelled</SelectItem>
                        <SelectItem value="returned">Returned</SelectItem>
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />

              {/* Marketplace */}
              <FormField
                control={form.control}
                name="marketplace"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Marketplace</FormLabel>
                    <Select onValueChange={field.onChange} value={field.value} disabled={isReadOnly}>
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder="Pilih marketplace" />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        <SelectItem value="Shopee">Shopee</SelectItem>
                        <SelectItem value="Tokopedia">Tokopedia</SelectItem>
                        <SelectItem value="Lazada">Lazada</SelectItem>
                        <SelectItem value="TikTok">TikTok</SelectItem>
                        <SelectItem value="Offline">Offline</SelectItem>
                        <SelectItem value="Other">Lainnya</SelectItem>
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />

              {/* Total Fees */}
              <FormField
                control={form.control}
                name="total_fees"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Total Fee (Admin + Ongkir)</FormLabel>
                    <FormControl>
                      <Input type="number" {...field} min={0} disabled={isReadOnly} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            {/* Order Items */}
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <FormLabel>Items *</FormLabel>
                {!isReadOnly && (
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={() => append({ variant_id: "", qty: 1, unit_price: 0, hpp: 0 })}
                  >
                    <Plus className="h-4 w-4 mr-1" />
                    Tambah Item
                  </Button>
                )}
              </div>

              {fields.map((field, index) => {
                const currentItem = form.watch(`items.${index}`);
                const subtotal = (currentItem?.qty || 0) * (currentItem?.unit_price || 0);
                const selectedVariant = variantOptions.find(v => v.id === currentItem?.variant_id);

                return (
                  <div key={field.id} className="space-y-2 p-3 bg-muted/30 rounded-lg border">
                    {/* Product Search - Full Width */}
                    <FormField
                      control={form.control}
                      name={`items.${index}.variant_id`}
                      render={({ field }) => (
                        <FormItem className="flex flex-col">
                          <FormLabel className="text-xs font-medium">Produk *</FormLabel>
                          <Popover>
                            <PopoverTrigger asChild>
                              <FormControl>
                                <Button
                                  disabled={isReadOnly}
                                  variant="outline"
                                  role="combobox"
                                  className={cn(
                                    "w-full justify-between h-9 font-normal",
                                    !field.value && "text-muted-foreground"
                                  )}
                                >
                                  {field.value ? (
                                    <span className="flex items-center gap-2 truncate">
                                      <PackageSearch className="h-3.5 w-3.5 shrink-0" />
                                      <span className="truncate">
                                        {selectedVariant?.productName} - {selectedVariant?.sku}
                                        {selectedVariant?.productType === 'service' && (
                                          <span className="ml-1 text-[10px] bg-sky-100 text-sky-700 px-1 rounded">Service</span>
                                        )}
                                      </span>
                                    </span>
                                  ) : (
                                    <span className="flex items-center gap-2">
                                      <PackageSearch className="h-3.5 w-3.5" />
                                      Cari produk...
                                    </span>
                                  )}
                                  <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
                                </Button>
                              </FormControl>
                            </PopoverTrigger>
                            <PopoverContent className="w-[400px] p-0" align="start">
                              <Command>
                                <CommandInput placeholder="Cari produk atau SKU..." />
                                <CommandList className="max-h-64 overflow-auto">
                                  <CommandEmpty>Produk tidak ditemukan.</CommandEmpty>
                                  <CommandGroup>
                                    {variantOptions.map((variant) => (
                                      <CommandItem
                                        key={variant.id}
                                        value={`${variant.productName} ${variant.sku}`}
                                        onSelect={() => {
                                          field.onChange(variant.id);
                                          handleVariantChange(index, variant.id);
                                        }}
                                        className="flex items-center justify-between"
                                      >
                                        <div className="flex items-center gap-2 flex-1 min-w-0">
                                          <Check
                                            className={cn(
                                              "h-4 w-4 shrink-0",
                                              variant.id === field.value ? "opacity-100" : "opacity-0"
                                            )}
                                          />
                                          <div className="flex flex-col min-w-0">
                                            <span className="text-sm font-medium truncate">{variant.productName}</span>
                                            <span className="text-xs text-muted-foreground">{variant.sku}</span>
                                          </div>
                                        </div>
                                        <div className="flex items-center gap-3 shrink-0">
                                          <div className="text-right">
                                            <div className="text-xs font-medium">Rp {variant.price.toLocaleString()}</div>
                                            <div className={cn(
                                              "text-[10px]",
                                              variant.stock > 10 ? "text-emerald-600" : variant.stock > 0 ? "text-orange-600" : "text-destructive"
                                            )}>
                                              Stok: {variant.stock}
                                            </div>
                                          </div>
                                        </div>
                                      </CommandItem>
                                    ))}
                                  </CommandGroup>
                                </CommandList>
                              </Command>
                            </PopoverContent>
                          </Popover>
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    {/* Qty, Unit Price, HPP in Row */}
                    <div className="grid grid-cols-12 gap-2 items-start">
                      <div className="col-span-3">
                        <FormField
                          control={form.control}
                          name={`items.${index}.qty`}
                          render={({ field }) => (
                            <FormItem>
                              <FormLabel className="text-xs">Qty</FormLabel>
                              <FormControl>
                                <Input type="number" {...field} min={1} className="h-9" disabled={isReadOnly} />
                              </FormControl>
                              <FormMessage />
                            </FormItem>
                          )}
                        />
                      </div>

                      <div className="col-span-4">
                        <FormField
                          control={form.control}
                          name={`items.${index}.unit_price`}
                          render={({ field }) => (
                            <FormItem>
                              <FormLabel className="text-xs">Harga</FormLabel>
                              <FormControl>
                                <Input type="number" {...field} min={0} className="h-9" />
                              </FormControl>
                              <FormMessage />
                            </FormItem>
                          )}
                        />
                      </div>

                      <div className="col-span-4">
                        <FormField
                          control={form.control}
                          name={`items.${index}.hpp`}
                          render={({ field }) => (
                            <FormItem>
                              <FormLabel className="text-xs">HPP</FormLabel>
                              <FormControl>
                                <Input
                                  type="number"
                                  {...field}
                                  min={0}
                                  className="h-9"
                                  disabled={isReadOnly || selectedVariant?.productType === 'service'}
                                  title={selectedVariant?.productType === 'service' ? "Service items have 0 HPP" : "Base HPP"}
                                />
                              </FormControl>
                              <FormMessage />
                            </FormItem>
                          )}
                        />
                      </div>

                      <div className="col-span-1 flex items-end">
                        <Button
                          type="button"
                          variant="ghost"
                          size="icon"
                          className="h-9 w-9"
                          onClick={() => fields.length > 1 && remove(index)}
                          disabled={fields.length === 1 || isReadOnly}
                        >
                          <Trash2 className="h-4 w-4 text-destructive" />
                        </Button>
                      </div>
                    </div>

                    {/* Subtotal Badge */}
                    {subtotal > 0 && (
                      <div className="flex justify-end">
                        <div className="text-xs bg-primary/10 text-primary px-2 py-1 rounded font-medium">
                          Subtotal: Rp {subtotal.toLocaleString("id-ID")}
                        </div>
                      </div>
                    )}
                  </div>
                );
              })}
              {form.formState.errors.items?.root && (
                <p className="text-sm text-destructive">
                  {form.formState.errors.items.root.message}
                </p>
              )}
            </div>

            {/* Summary */}
            <div className="p-4 bg-muted/50 rounded-lg space-y-2">
              <div className="flex justify-between text-sm">
                <span>Total Amount:</span>
                <span className="font-medium">Rp {totalAmount.toLocaleString("id-ID")}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span>Total HPP:</span>
                <span className="font-medium">Rp {totalHpp.toLocaleString("id-ID")}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span>Total Fee:</span>
                <span className="font-medium">Rp {totalFees.toLocaleString("id-ID")}</span>
              </div>
              <div className="flex justify-between text-sm font-semibold border-t pt-2">
                <span>Profit:</span>
                <span className={profit >= 0 ? "text-emerald-600" : "text-destructive"}>
                  Rp {profit.toLocaleString("id-ID")}
                </span>
              </div>
            </div>

            <div className="flex justify-between gap-2">
              {initialData?.status === 'completed' && (
                <div className="flex gap-2">
                  <Button
                    type="button"
                    variant="destructive"
                    onClick={() => setShowReturnDialog(true)}
                  >
                    Retur Barang
                  </Button>
                  <Button
                    type="button"
                    variant="outline"
                    className="border-dashed"
                    onClick={() => {
                      window.location.href = `/accounting?tab=journals&ref_id=${initialData.id}`;
                    }}
                  >
                    Lihat Jurnal
                  </Button>
                </div>
              )}

              <div className="flex gap-2 ml-auto">
                <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>
                  Tutup
                </Button>
                {!isReadOnly && (
                  <Button type="submit" disabled={createOrder.isPending || updateOrder.isPending}>
                    {createOrder.isPending || updateOrder.isPending ? "Menyimpan..." : "Simpan Sales Order"}
                  </Button>
                )}
              </div>
            </div>
          </form>
        </Form>
      </DialogContent>

      <SalesReturnDialog
        open={showReturnDialog}
        onOpenChange={setShowReturnDialog}
        order={initialData}
      />
    </Dialog >
  );
}
